
import '@testing-library/jest-dom';
import dayjs from '../src/dayjs';
import { Chronos, Schedule, Event, Events } from '../src';


test('preview of assignment', async () => {

    const assignments = [
        {
            id: 439274,
            description: '<link rel="stylesheet" href="https://instructure-uploads.s3.amazonaws.com/account_60780000000000001/attachments/2440678/canvas_global_app.css"><p><a title="Module 1" href="https://wustl.instructure.com/courses/91022/pages/module-1" data-api-endpoint="https://wustl.instructure.com/api/v1/courses/91022/pages/module-1" data-api-returntype="Page">Module 1</a></p><script src="https://instructure-uploads.s3.amazonaws.com/account_60780000000000001/attachments/2440677/canvas_global_app_AS.js"></script>',
            due_at: '2022-09-07T17:50:00Z',
            unlock_at: null,
            lock_at: null,
            points_possible: 50,
            grading_type: 'points',
            assignment_group_id: 137171,
            grading_standard_id: null,
            created_at: '2022-08-22T14:26:17Z',
            updated_at: '2022-08-23T15:54:49Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 1,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: null,
            hide_in_gradebook: false,
            secure_params: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6IjIwYjdkOTM5LWE0ODctNGE5Ny1iMTIzLTI2OWU3NzYxMzExZSIsImx0aV9hc3NpZ25tZW50X2Rlc2NyaXB0aW9uIjoiXHUwMDNjcFx1MDAzZVx1MDAzY2EgdGl0bGU9XCJNb2R1bGUgMVwiIGhyZWY9XCIvY291cnNlcy85MTAyMi9wYWdlcy9tb2R1bGUtMVwiXHUwMDNlTW9kdWxlIDFcdTAwM2MvYVx1MDAzZVx1MDAzYy9wXHUwMDNlIn0.NxrMxGmJJgV0lVCpZKqcgny1gnwvdpVAKIUTgi6Tiro',
            lti_context_id: '20b7d939-a487-4a97-b123-269e7761311e',
            course_id: 91022,
            name: 'Module 1',
            submission_types: ['none'],
            has_submitted_submissions: false,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: true,
            is_quiz_assignment: false,
            can_duplicate: true,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: true,
            html_url: 'https://wustl.instructure.com/courses/91022/assignments/439274',
            published: true,
            only_visible_to_overrides: false,
            visible_to_everyone: true,
            locked_for_user: false,
            submissions_download_url: 'https://wustl.instructure.com/courses/91022/assignments/439274/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false
        },
        {
            id: 439276,
            description: '<link rel="stylesheet" href="https://instructure-uploads.s3.amazonaws.com/account_60780000000000001/attachments/2440678/canvas_global_app.css"><p><a title="Module 2" href="https://wustl.instructure.com/courses/91022/pages/module-2" data-api-endpoint="https://wustl.instructure.com/api/v1/courses/91022/pages/module-2" data-api-returntype="Page">Module 2</a></p><script src="https://instructure-uploads.s3.amazonaws.com/account_60780000000000001/attachments/2440677/canvas_global_app_AS.js"></script>',
            due_at: '2022-09-19T17:50:00Z',
            unlock_at: null,
            lock_at: null,
            points_possible: 65,
            grading_type: 'points',
            assignment_group_id: 137171,
            grading_standard_id: null,
            created_at: '2022-08-22T14:26:18Z',
            updated_at: '2022-08-23T15:55:14Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 2,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: null,
            hide_in_gradebook: false,
            secure_params: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6ImM3OTMxYTc5LTFlODAtNGY5My1iY2Q4LWI0NzkyOGYzMWQ4ZiIsImx0aV9hc3NpZ25tZW50X2Rlc2NyaXB0aW9uIjoiXHUwMDNjcFx1MDAzZVx1MDAzY2EgdGl0bGU9XCJNb2R1bGUgMlwiIGhyZWY9XCIvY291cnNlcy85MTAyMi9wYWdlcy9tb2R1bGUtMlwiXHUwMDNlTW9kdWxlIDJcdTAwM2MvYVx1MDAzZVx1MDAzYy9wXHUwMDNlIn0.Z9x2a34fHOann-ZBfgM3ZzmqWc6qI88hfosKCitfJzs',
            lti_context_id: 'c7931a79-1e80-4f93-bcd8-b47928f31d8f',
            course_id: 91022,
            name: 'Module 2 Individual',
            submission_types: ['none'],
            has_submitted_submissions: false,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: true,
            is_quiz_assignment: false,
            can_duplicate: true,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: true,
            html_url: 'https://wustl.instructure.com/courses/91022/assignments/439276',
            published: true,
            only_visible_to_overrides: false,
            visible_to_everyone: true,
            locked_for_user: false,
            submissions_download_url: 'https://wustl.instructure.com/courses/91022/assignments/439276/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false
        },
        {
            id: 439275,
            description: '<link rel="stylesheet" href="https://instructure-uploads.s3.amazonaws.com/account_60780000000000001/attachments/2440678/canvas_global_app.css"><p><a title="Module 2" href="https://wustl.instructure.com/courses/91022/pages/module-2" data-api-endpoint="https://wustl.instructure.com/api/v1/courses/91022/pages/module-2" data-api-returntype="Page">Module 2</a></p><script src="https://instructure-uploads.s3.amazonaws.com/account_60780000000000001/attachments/2440677/canvas_global_app_AS.js"></script>',
            due_at: '2022-09-19T17:50:00Z',
            unlock_at: null,
            lock_at: null,
            points_possible: 55,
            grading_type: 'points',
            assignment_group_id: 137171,
            grading_standard_id: null,
            created_at: '2022-08-22T14:26:17Z',
            updated_at: '2022-08-23T15:55:26Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 3,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: null,
            hide_in_gradebook: false,
            secure_params: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6IjY1NDdkNTM1LWUyZjktNGIyNy1iNjE1LWE1YTNlZDQ5N2VjNCIsImx0aV9hc3NpZ25tZW50X2Rlc2NyaXB0aW9uIjoiXHUwMDNjcFx1MDAzZVx1MDAzY2EgdGl0bGU9XCJNb2R1bGUgMlwiIGhyZWY9XCIvY291cnNlcy85MTAyMi9wYWdlcy9tb2R1bGUtMlwiXHUwMDNlTW9kdWxlIDJcdTAwM2MvYVx1MDAzZVx1MDAzYy9wXHUwMDNlIn0.Nw1GtsHiA-_wpmfegn44IeoQm4BH2Fd5JTsFvxdca6g',
            lti_context_id: '6547d535-e2f9-4b27-b615-a5a3ed497ec4',
            course_id: 91022,
            name: 'Module 2 Group',
            submission_types: ['none'],
            has_submitted_submissions: false,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: true,
            is_quiz_assignment: false,
            can_duplicate: true,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: true,
            html_url: 'https://wustl.instructure.com/courses/91022/assignments/439275',
            published: true,
            only_visible_to_overrides: false,
            visible_to_everyone: true,
            locked_for_user: false,
            submissions_download_url: 'https://wustl.instructure.com/courses/91022/assignments/439275/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false
        },
        {
            id: 439278,
            description: '<link rel="stylesheet" href="https://instructure-uploads.s3.amazonaws.com/account_60780000000000001/attachments/2440678/canvas_global_app.css"><p><a title="Module 3" href="https://wustl.instructure.com/courses/91022/pages/module-3" data-api-endpoint="https://wustl.instructure.com/api/v1/courses/91022/pages/module-3" data-api-returntype="Page">Module 3</a></p><script src="https://instructure-uploads.s3.amazonaws.com/account_60780000000000001/attachments/2440677/canvas_global_app_AS.js"></script>',
            due_at: '2022-10-03T17:50:00Z',
            unlock_at: null,
            lock_at: null,
            points_possible: 25,
            grading_type: 'points',
            assignment_group_id: 137171,
            grading_standard_id: null,
            created_at: '2022-08-22T14:26:18Z',
            updated_at: '2022-08-23T15:55:47Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 4,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: null,
            hide_in_gradebook: false,
            secure_params: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6ImE2NGRhNzBlLWFlMWYtNDZlNC1iZWM5LTQwMDM4ZjE2YWY1NSIsImx0aV9hc3NpZ25tZW50X2Rlc2NyaXB0aW9uIjoiXHUwMDNjcFx1MDAzZVx1MDAzY2EgdGl0bGU9XCJNb2R1bGUgM1wiIGhyZWY9XCIvY291cnNlcy85MTAyMi9wYWdlcy9tb2R1bGUtM1wiXHUwMDNlTW9kdWxlIDNcdTAwM2MvYVx1MDAzZVx1MDAzYy9wXHUwMDNlIn0.GRVz8vvbPGHy-8eTIhukKeQBRlSL67hYd-JMQpO5qU4',
            lti_context_id: 'a64da70e-ae1f-46e4-bec9-40038f16af55',
            course_id: 91022,
            name: 'Module 3 Individual',
            submission_types: ['none'],
            has_submitted_submissions: false,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: true,
            is_quiz_assignment: false,
            can_duplicate: true,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: true,
            html_url: 'https://wustl.instructure.com/courses/91022/assignments/439278',
            published: true,
            only_visible_to_overrides: false,
            visible_to_everyone: true,
            locked_for_user: false,
            submissions_download_url: 'https://wustl.instructure.com/courses/91022/assignments/439278/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false
        },
        {
            id: 439277,
            description: '<link rel="stylesheet" href="https://instructure-uploads.s3.amazonaws.com/account_60780000000000001/attachments/2440678/canvas_global_app.css"><p><a title="Module 3" href="https://wustl.instructure.com/courses/91022/pages/module-3" data-api-endpoint="https://wustl.instructure.com/api/v1/courses/91022/pages/module-3" data-api-returntype="Page">Module 3</a></p><script src="https://instructure-uploads.s3.amazonaws.com/account_60780000000000001/attachments/2440677/canvas_global_app_AS.js"></script>',
            due_at: '2022-10-03T17:50:00Z',
            unlock_at: null,
            lock_at: null,
            points_possible: 75,
            grading_type: 'points',
            assignment_group_id: 137171,
            grading_standard_id: null,
            created_at: '2022-08-22T14:26:18Z',
            updated_at: '2022-08-23T15:55:54Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 5,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: null,
            hide_in_gradebook: false,
            secure_params: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6IjU4YmVlZDFiLTdiOWQtNDNkOC04NmQ2LTJkZmRlY2NmNjY3MCIsImx0aV9hc3NpZ25tZW50X2Rlc2NyaXB0aW9uIjoiXHUwMDNjcFx1MDAzZVx1MDAzY2EgdGl0bGU9XCJNb2R1bGUgM1wiIGhyZWY9XCIvY291cnNlcy85MTAyMi9wYWdlcy9tb2R1bGUtM1wiXHUwMDNlTW9kdWxlIDNcdTAwM2MvYVx1MDAzZVx1MDAzYy9wXHUwMDNlIn0.4cs2LqXqilo0mDoD7KphNPC-OvtJMVa2_xxEIEd_3Ys',
            lti_context_id: '58beed1b-7b9d-43d8-86d6-2dfdeccf6670',
            course_id: 91022,
            name: 'Module 3 Group',
            submission_types: ['none'],
            has_submitted_submissions: false,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: true,
            is_quiz_assignment: false,
            can_duplicate: true,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: true,
            html_url: 'https://wustl.instructure.com/courses/91022/assignments/439277',
            published: true,
            only_visible_to_overrides: false,
            visible_to_everyone: true,
            locked_for_user: false,
            submissions_download_url: 'https://wustl.instructure.com/courses/91022/assignments/439277/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false
        },
        {
            id: 439279,
            description: '<link rel="stylesheet" href="https://instructure-uploads.s3.amazonaws.com/account_60780000000000001/attachments/2440678/canvas_global_app.css"><p><a title="Module 4" href="https://wustl.instructure.com/courses/91022/pages/module-4" data-api-endpoint="https://wustl.instructure.com/api/v1/courses/91022/pages/module-4" data-api-returntype="Page">Module 4</a></p><script src="https://instructure-uploads.s3.amazonaws.com/account_60780000000000001/attachments/2440677/canvas_global_app_AS.js"></script>',
            due_at: '2022-10-12T17:50:00Z',
            unlock_at: null,
            lock_at: null,
            points_possible: 50,
            grading_type: 'points',
            assignment_group_id: 137171,
            grading_standard_id: null,
            created_at: '2022-08-22T14:26:18Z',
            updated_at: '2022-08-23T15:56:11Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 6,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: null,
            hide_in_gradebook: false,
            secure_params: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6ImJjZmQ1ZTAzLTQyZjItNDcyMS1hMTNmLTYyMzQyNDY4NjU0MSIsImx0aV9hc3NpZ25tZW50X2Rlc2NyaXB0aW9uIjoiXHUwMDNjcFx1MDAzZVx1MDAzY2EgdGl0bGU9XCJNb2R1bGUgNFwiIGhyZWY9XCIvY291cnNlcy85MTAyMi9wYWdlcy9tb2R1bGUtNFwiXHUwMDNlTW9kdWxlIDRcdTAwM2MvYVx1MDAzZVx1MDAzYy9wXHUwMDNlIn0.HXEygo3Dh0t2xD97NZSmptvuINTRR0AVGKRF2rEvugo',
            lti_context_id: 'bcfd5e03-42f2-4721-a13f-623424686541',
            course_id: 91022,
            name: 'Module 4',
            submission_types: ['none'],
            has_submitted_submissions: false,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: true,
            is_quiz_assignment: false,
            can_duplicate: true,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: true,
            html_url: 'https://wustl.instructure.com/courses/91022/assignments/439279',
            published: true,
            only_visible_to_overrides: false,
            visible_to_everyone: true,
            locked_for_user: false,
            submissions_download_url: 'https://wustl.instructure.com/courses/91022/assignments/439279/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false
        },
        {
            id: 439281,
            description: '<link rel="stylesheet" href="https://instructure-uploads.s3.amazonaws.com/account_60780000000000001/attachments/2440678/canvas_global_app.css"><p><a title="Module 5" href="https://wustl.instructure.com/courses/91022/pages/module-5" data-api-endpoint="https://wustl.instructure.com/api/v1/courses/91022/pages/module-5" data-api-returntype="Page">Module 5</a></p><script src="https://instructure-uploads.s3.amazonaws.com/account_60780000000000001/attachments/2440677/canvas_global_app_AS.js"></script>',
            due_at: '2022-10-26T17:50:00Z',
            unlock_at: null,
            lock_at: null,
            points_possible: 25,
            grading_type: 'points',
            assignment_group_id: 137171,
            grading_standard_id: null,
            created_at: '2022-08-22T14:26:19Z',
            updated_at: '2022-08-23T15:56:34Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 7,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: null,
            hide_in_gradebook: false,
            secure_params: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6IjM4MzFiOGE2LTYzOGUtNDllYy1iMzljLTBmNmVkMGFiNjkzZiIsImx0aV9hc3NpZ25tZW50X2Rlc2NyaXB0aW9uIjoiXHUwMDNjcFx1MDAzZVx1MDAzY2EgdGl0bGU9XCJNb2R1bGUgNVwiIGhyZWY9XCIvY291cnNlcy85MTAyMi9wYWdlcy9tb2R1bGUtNVwiIGRhdGEtYXBpLWVuZHBvaW50PVwiaHR0cHM6Ly93dXN0bC5pbnN0cnVjdHVyZS5jb20vYXBpL3YxL2NvdXJzZXMvNDcyNzIvcGFnZXMvbW9kdWxlLTVcIiBkYXRhLWFwaS1yZXR1cm50eXBlPVwiUGFnZVwiXHUwMDNlTW9kdWxlIDVcdTAwM2MvYVx1MDAzZVx1MDAzYy9wXHUwMDNlIn0.C0a_BTJy_74OS_qW6YF7A_4tUrDlaDqUSAQZYTmIUn4',
            lti_context_id: '3831b8a6-638e-49ec-b39c-0f6ed0ab693f',
            course_id: 91022,
            name: 'Module 5 Individual',
            submission_types: ['none'],
            has_submitted_submissions: false,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: true,
            is_quiz_assignment: false,
            can_duplicate: true,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: true,
            html_url: 'https://wustl.instructure.com/courses/91022/assignments/439281',
            published: true,
            only_visible_to_overrides: false,
            visible_to_everyone: true,
            locked_for_user: false,
            submissions_download_url: 'https://wustl.instructure.com/courses/91022/assignments/439281/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false
        },
        {
            id: 439280,
            description: '<link rel="stylesheet" href="https://instructure-uploads.s3.amazonaws.com/account_60780000000000001/attachments/2440678/canvas_global_app.css"><p><a title="Module 5" href="https://wustl.instructure.com/courses/91022/pages/module-5" data-api-endpoint="https://wustl.instructure.com/api/v1/courses/91022/pages/module-5" data-api-returntype="Page">Module 5</a></p><script src="https://instructure-uploads.s3.amazonaws.com/account_60780000000000001/attachments/2440677/canvas_global_app_AS.js"></script>',
            due_at: '2022-10-26T17:50:00Z',
            unlock_at: null,
            lock_at: null,
            points_possible: 75,
            grading_type: 'points',
            assignment_group_id: 137171,
            grading_standard_id: null,
            created_at: '2022-08-22T14:26:19Z',
            updated_at: '2022-08-23T15:56:51Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 8,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: null,
            hide_in_gradebook: false,
            secure_params: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6IjBmMzMwMGEzLTI4OWQtNGE5My1iNTY4LTVkNGUzOTdlODhlZSIsImx0aV9hc3NpZ25tZW50X2Rlc2NyaXB0aW9uIjoiXHUwMDNjcFx1MDAzZVx1MDAzY2EgdGl0bGU9XCJNb2R1bGUgNVwiIGhyZWY9XCIvY291cnNlcy85MTAyMi9wYWdlcy9tb2R1bGUtNVwiXHUwMDNlTW9kdWxlIDVcdTAwM2MvYVx1MDAzZVx1MDAzYy9wXHUwMDNlIn0.3iIva5iqIZNyP27ek-X767i2k-BUS2pvTLb4WBzol3Q',
            lti_context_id: '0f3300a3-289d-4a93-b568-5d4e397e88ee',
            course_id: 91022,
            name: 'Module 5 Group',
            submission_types: ['none'],
            has_submitted_submissions: false,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: true,
            is_quiz_assignment: false,
            can_duplicate: true,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: true,
            html_url: 'https://wustl.instructure.com/courses/91022/assignments/439280',
            published: true,
            only_visible_to_overrides: false,
            visible_to_everyone: true,
            locked_for_user: false,
            submissions_download_url: 'https://wustl.instructure.com/courses/91022/assignments/439280/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false
        },
        {
            id: 439283,
            description: '<link rel="stylesheet" href="https://instructure-uploads.s3.amazonaws.com/account_60780000000000001/attachments/2440678/canvas_global_app.css"><p><a title="Module 6" href="https://wustl.instructure.com/courses/91022/pages/module-6" data-api-endpoint="https://wustl.instructure.com/api/v1/courses/91022/pages/module-6" data-api-returntype="Page">Module 6</a></p><script src="https://instructure-uploads.s3.amazonaws.com/account_60780000000000001/attachments/2440677/canvas_global_app_AS.js"></script>',
            due_at: '2022-11-07T18:50:00Z',
            unlock_at: null,
            lock_at: null,
            points_possible: 25,
            grading_type: 'points',
            assignment_group_id: 137171,
            grading_standard_id: null,
            created_at: '2022-08-22T14:26:19Z',
            updated_at: '2022-08-23T15:57:09Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 9,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: null,
            hide_in_gradebook: false,
            secure_params: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6ImFlYmQ3MDc4LWE5YzItNDEyOC05MmNiLTgyOTA5NWJmN2FiMyIsImx0aV9hc3NpZ25tZW50X2Rlc2NyaXB0aW9uIjoiXHUwMDNjcFx1MDAzZVx1MDAzY2EgdGl0bGU9XCJNb2R1bGUgNlwiIGhyZWY9XCIvY291cnNlcy85MTAyMi9wYWdlcy9tb2R1bGUtNlwiXHUwMDNlTW9kdWxlIDZcdTAwM2MvYVx1MDAzZVx1MDAzYy9wXHUwMDNlIn0.S8SsdipHCLvXEfw3WxvJeoEhp5Hs05wlpX5Ha3NaOTU',
            lti_context_id: 'aebd7078-a9c2-4128-92cb-829095bf7ab3',
            course_id: 91022,
            name: 'Module 6 Individual',
            submission_types: ['none'],
            has_submitted_submissions: false,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: true,
            is_quiz_assignment: false,
            can_duplicate: true,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: true,
            html_url: 'https://wustl.instructure.com/courses/91022/assignments/439283',
            published: true,
            only_visible_to_overrides: false,
            visible_to_everyone: true,
            locked_for_user: false,
            submissions_download_url: 'https://wustl.instructure.com/courses/91022/assignments/439283/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false
        },
        {
            id: 439282,
            description: '',
            due_at: '2022-11-07T18:50:00Z',
            unlock_at: null,
            lock_at: null,
            points_possible: 50,
            grading_type: 'points',
            assignment_group_id: 137171,
            grading_standard_id: null,
            created_at: '2022-08-22T14:26:19Z',
            updated_at: '2022-08-23T15:57:16Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 10,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: null,
            hide_in_gradebook: false,
            secure_params: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6ImI3YTkxNjNiLTRkZjEtNGIyNS05YjRkLWExZmViNGJiMTQxNiJ9.SaSRdHUb2S3vZWt_Ere7EqNJ92bsLvgiQIO5BGvqDuU',
            lti_context_id: 'b7a9163b-4df1-4b25-9b4d-a1feb4bb1416',
            course_id: 91022,
            name: 'Module 6 Group',
            submission_types: ['none'],
            has_submitted_submissions: false,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: true,
            is_quiz_assignment: false,
            can_duplicate: true,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: true,
            html_url: 'https://wustl.instructure.com/courses/91022/assignments/439282',
            published: true,
            only_visible_to_overrides: false,
            visible_to_everyone: true,
            locked_for_user: false,
            submissions_download_url: 'https://wustl.instructure.com/courses/91022/assignments/439282/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false
        },
        {
            id: 439285,
            description: '<link rel="stylesheet" href="https://instructure-uploads.s3.amazonaws.com/account_60780000000000001/attachments/2440678/canvas_global_app.css"><p><a title="Module 7 (Creative Project)" href="https://wustl.instructure.com/courses/91022/pages/module-7-creative-project" data-api-endpoint="https://wustl.instructure.com/api/v1/courses/91022/pages/module-7-creative-project" data-api-returntype="Page">Module 7 (Creative Project)</a></p><script src="https://instructure-uploads.s3.amazonaws.com/account_60780000000000001/attachments/2440677/canvas_global_app_AS.js"></script>',
            due_at: '2022-11-09T18:50:00Z',
            unlock_at: null,
            lock_at: null,
            points_possible: 5,
            grading_type: 'points',
            assignment_group_id: 137171,
            grading_standard_id: null,
            created_at: '2022-08-22T14:26:20Z',
            updated_at: '2022-08-23T15:57:30Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 11,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: null,
            hide_in_gradebook: false,
            secure_params: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6IjhmMTFmYzAwLTdiODItNGQ5NC1iZmY1LTkwMTc0MWQ4NGE4OSIsImx0aV9hc3NpZ25tZW50X2Rlc2NyaXB0aW9uIjoiXHUwMDNjcFx1MDAzZVx1MDAzY2EgdGl0bGU9XCJNb2R1bGUgNyAoQ3JlYXRpdmUgUHJvamVjdClcIiBocmVmPVwiL2NvdXJzZXMvOTEwMjIvcGFnZXMvbW9kdWxlLTctY3JlYXRpdmUtcHJvamVjdFwiXHUwMDNlTW9kdWxlIDcgKENyZWF0aXZlIFByb2plY3QpXHUwMDNjL2FcdTAwM2VcdTAwM2MvcFx1MDAzZSJ9.IAKoQtmyrZrU136ks7AkyYBVEnd4V2BR1uNAU7l0GtA',
            lti_context_id: '8f11fc00-7b82-4d94-bff5-901741d84a89',
            course_id: 91022,
            name: 'Module 7 (Creative Project) Description',
            submission_types: ['none'],
            has_submitted_submissions: false,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: true,
            is_quiz_assignment: false,
            can_duplicate: true,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: true,
            html_url: 'https://wustl.instructure.com/courses/91022/assignments/439285',
            published: true,
            only_visible_to_overrides: false,
            visible_to_everyone: true,
            locked_for_user: false,
            submissions_download_url: 'https://wustl.instructure.com/courses/91022/assignments/439285/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false
        },
        {
            id: 439284,
            description: '<link rel="stylesheet" href="https://instructure-uploads.s3.amazonaws.com/account_60780000000000001/attachments/2440678/canvas_global_app.css"><p><a title="Module 7 (Creative Project)" href="https://wustl.instructure.com/courses/91022/pages/module-7-creative-project" data-api-endpoint="https://wustl.instructure.com/api/v1/courses/91022/pages/module-7-creative-project" data-api-returntype="Page">Module 7 (Creative Project)</a></p><script src="https://instructure-uploads.s3.amazonaws.com/account_60780000000000001/attachments/2440677/canvas_global_app_AS.js"></script>',
            due_at: '2022-12-07T18:50:00Z',
            unlock_at: null,
            lock_at: null,
            points_possible: 95,
            grading_type: 'points',
            assignment_group_id: 137171,
            grading_standard_id: null,
            created_at: '2022-08-22T14:26:19Z',
            updated_at: '2022-08-23T15:57:48Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 12,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: null,
            hide_in_gradebook: false,
            secure_params: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6IjdjODJlMzllLWZhOGYtNDVhYS1hY2EzLTJkNjY5OThkYTllOCIsImx0aV9hc3NpZ25tZW50X2Rlc2NyaXB0aW9uIjoiXHUwMDNjcFx1MDAzZVx1MDAzY2EgdGl0bGU9XCJNb2R1bGUgNyAoQ3JlYXRpdmUgUHJvamVjdClcIiBocmVmPVwiL2NvdXJzZXMvOTEwMjIvcGFnZXMvbW9kdWxlLTctY3JlYXRpdmUtcHJvamVjdFwiXHUwMDNlTW9kdWxlIDcgKENyZWF0aXZlIFByb2plY3QpXHUwMDNjL2FcdTAwM2VcdTAwM2MvcFx1MDAzZSJ9.cTDU-qQY7gaaX2ys2ZE2SyCj5qx2qNC9H4RjFdu7JRg',
            lti_context_id: '7c82e39e-fa8f-45aa-aca3-2d66998da9e8',
            course_id: 91022,
            name: 'Module 7 (Creative Project)',
            submission_types: ['none'],
            has_submitted_submissions: false,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: true,
            is_quiz_assignment: false,
            can_duplicate: true,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: true,
            html_url: 'https://wustl.instructure.com/courses/91022/assignments/439284',
            published: true,
            only_visible_to_overrides: false,
            visible_to_everyone: true,
            locked_for_user: false,
            submissions_download_url: 'https://wustl.instructure.com/courses/91022/assignments/439284/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false
        },
        {
            id: 439273,
            description: '<link rel="stylesheet" href="https://instructure-uploads.s3.amazonaws.com/account_60780000000000001/attachments/2440678/canvas_global_app.css"><p>This assignment is only for CSE 503 students.</p>\n' +
                '<p>&nbsp;</p>\n' +
                '<p><a title="CSE 503 Performance Evaluation" href="https://wustl.instructure.com/courses/91022/pages/cse-503-performance-evaluation" data-api-endpoint="https://wustl.instructure.com/api/v1/courses/91022/pages/cse-503-performance-evaluation" data-api-returntype="Page">CSE 503 Performance Evaluation</a></p><script src="https://instructure-uploads.s3.amazonaws.com/account_60780000000000001/attachments/2440677/canvas_global_app_AS.js"></script>',
            due_at: '2022-12-10T05:59:59Z',
            unlock_at: null,
            lock_at: null,
            points_possible: 60,
            grading_type: 'points',
            assignment_group_id: 137171,
            grading_standard_id: null,
            created_at: '2022-08-22T14:26:17Z',
            updated_at: '2022-08-23T15:58:10Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 13,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: null,
            hide_in_gradebook: false,
            secure_params: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6IjRiOTE0OGFhLTYzNTktNGM0OS1iZWQ2LTRmNTFmMWEyZTBlZCIsImx0aV9hc3NpZ25tZW50X2Rlc2NyaXB0aW9uIjoiXHUwMDNjcFx1MDAzZVRoaXMgYXNzaWdubWVudCBpcyBvbmx5IGZvciBDU0UgNTAzIHN0dWRlbnRzLlx1MDAzYy9wXHUwMDNlXG5cdTAwM2NwXHUwMDNlXHUwMDI2bmJzcDtcdTAwM2MvcFx1MDAzZVxuXHUwMDNjcFx1MDAzZVx1MDAzY2EgdGl0bGU9XCJDU0UgNTAzIFBlcmZvcm1hbmNlIEV2YWx1YXRpb25cIiBocmVmPVwiL2NvdXJzZXMvOTEwMjIvcGFnZXMvY3NlLTUwMy1wZXJmb3JtYW5jZS1ldmFsdWF0aW9uXCJcdTAwM2VDU0UgNTAzIFBlcmZvcm1hbmNlIEV2YWx1YXRpb25cdTAwM2MvYVx1MDAzZVx1MDAzYy9wXHUwMDNlIn0.Mit1IZIlE7hNx_yk4tpDMCodEhnAv4KcxbEjB8pvJ6o',
            lti_context_id: '4b9148aa-6359-4c49-bed6-4f51f1a2e0ed',
            course_id: 91022,
            name: 'CSE 503 Performance Evaluation',
            submission_types: ['none'],
            has_submitted_submissions: false,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: true,
            is_quiz_assignment: false,
            can_duplicate: true,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: true,
            html_url: 'https://wustl.instructure.com/courses/91022/assignments/439273',
            published: true,
            only_visible_to_overrides: false,
            visible_to_everyone: true,
            locked_for_user: false,
            submissions_download_url: 'https://wustl.instructure.com/courses/91022/assignments/439273/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false
        }];

    const assignment = assignments[assignments.length - 1];

    const date = dayjs(assignment.due_at).utc();
    console.log(JSON.stringify({
        name: assignment.name,
        raw: assignment.due_at,
        tz: {
            offset: dayjs().getTimezoneOffsetInHours(),
            name: dayjs().tz.name
        },
        utc: {
            date: date.format("MMM DD, YYYY, h:mm:ss"),
            chronos: date.toChronos()
        },
        local: {
            date: date.tz('America/Chicago').format("MMM DD, YYYY, h:mm:ss"),
            chronos: date.tz('America/Chicago').toLocalChronos()
        }
    }, null, 2))

    expect(1).toBe(1)
});

test('make event', async () => {
    const newEvent = new Event({
        name: "Test",
        date: 20250106,
        start_time: String(3),
        end_time: String(4),
        is_local: false
    });
    newEvent.when();

    const copy = newEvent.copy();
    copy.localize();
    copy.when();

    const again = copy.copy();
    again.globalize();
    again.when();
    expect(1).toBe(1);
})


test('sort by date.', async () => {
    const test = [
        {
            "type": "Event",
            "uuid": "1b28ad3d-f79b-4f22-bb2f-7bbc325bd615",
            "name": "Break for Fourth of July",
            "location_name": null,
            "location_address": null,
            "location_place_id": null,
            "end_location_name": null,
            "end_location_address": null,
            "end_location_place_id": null,
            "start_time": null,
            "end_time": null,
            "date": 20250704,
            "end_date": 20250706,
            "cover_img": null,
            "icon_img": null,
            "wordmark_img": null,
            "attachment_img": null,
            "theme_color": "#31777e",
            "search_vectors": "'31777e':6 'break':1 'fourth':3 'juli':5",
            "event_type": "standard",
            "link": null,
            "quantity": null,
            "capacity": null,
            "subtitle": null,
            "integration": null,
            "data_store": null,
            "junctions": [],
            "schedules": [],
            "children": [],
            "metadata": {},
            "isVisible": false,
            "version": 0,
            "attendees": null
        },
        {
            "type": "Event",
            "uuid": "8ddd9353-966f-4acb-bbb6-5424e55c2517",
            "name": "No Meetings",
            "location_name": null,
            "location_address": null,
            "location_place_id": null,
            "end_location_name": null,
            "end_location_address": null,
            "end_location_place_id": null,
            "start_time": null,
            "end_time": null,
            "date": 20250620,
            "end_date": 20250620,
            "cover_img": null,
            "icon_img": null,
            "wordmark_img": null,
            "attachment_img": null,
            "theme_color": "#31777e",
            "search_vectors": "'31777e':3 'meet':2",
            "event_type": "standard",
            "link": null,
            "quantity": null,
            "capacity": null,
            "subtitle": null,
            "integration": null,
            "data_store": null,
            "junctions": [],
            "schedules": [],
            "children": [],
            "metadata": {},
            "isVisible": false,
            "version": 0,
            "attendees": null
        },
        {
            "type": "Event",
            "uuid": "c34afc22-da69-48db-a383-706982936796",
            "name": "Last Day",
            "location_name": null,
            "location_address": null,
            "location_place_id": null,
            "end_location_name": null,
            "end_location_address": null,
            "end_location_place_id": null,
            "start_time": null,
            "end_time": null,
            "date": 20250815,
            "end_date": 20250815,
            "cover_img": null,
            "icon_img": null,
            "wordmark_img": null,
            "attachment_img": null,
            "theme_color": "#31777e",
            "search_vectors": "'31777e':3 'day':2 'last':1",
            "event_type": "standard",
            "link": null,
            "quantity": null,
            "capacity": null,
            "subtitle": null,
            "integration": null,
            "data_store": null,
            "junctions": [],
            "schedules": [],
            "children": [],
            "metadata": {},
            "isVisible": false,
            "version": 0,
            "attendees": null
        },
        {
            "type": "Event",
            "uuid": "ccaec48a-3c1c-4ae5-9cc8-eebb1a33d2cc",
            "name": "First Day",
            "location_name": null,
            "location_address": null,
            "location_place_id": null,
            "end_location_name": null,
            "end_location_address": null,
            "end_location_place_id": null,
            "start_time": null,
            "end_time": null,
            "date": 20250609,
            "end_date": 20250609,
            "cover_img": null,
            "icon_img": null,
            "wordmark_img": null,
            "attachment_img": null,
            "theme_color": "#31777e",
            "search_vectors": "'31777e':3 'day':2 'first':1",
            "event_type": "standard",
            "link": null,
            "quantity": null,
            "capacity": null,
            "subtitle": null,
            "integration": null,
            "data_store": null,
            "junctions": [],
            "schedules": [],
            "children": [],
            "metadata": {},
            "isVisible": false,
            "version": 0,
            "attendees": null
        },
        {
            "type": "Event",
            "uuid": "d3cbbd3c-3e5e-4568-969a-305f305d861d",
            "name": "Juneteeth (No Meetings)",
            "location_name": null,
            "location_address": null,
            "location_place_id": null,
            "end_location_name": null,
            "end_location_address": null,
            "end_location_place_id": null,
            "start_time": null,
            "end_time": null,
            "date": 20250619,
            "end_date": 20250619,
            "cover_img": null,
            "icon_img": null,
            "wordmark_img": null,
            "attachment_img": null,
            "theme_color": "#31777e",
            "search_vectors": "'31777e':4 'juneteeth':1 'meet':3",
            "event_type": "standard",
            "link": null,
            "quantity": null,
            "capacity": null,
            "subtitle": null,
            "integration": null,
            "data_store": null,
            "junctions": [],
            "schedules": [],
            "children": [],
            "metadata": {},
            "isVisible": false,
            "version": 0,
            "attendees": null
        }
    ]

    const copy = [...test];
    const built = test.map((x: any) => new Event(x, true));
    built.sort(Events.sortByDate)
    console.log({
        before: copy.map(x => x.name),
        after: built.map(x => x.name)
    });

})